### ISSUE TITLE
Errors under load for LibUvServerFactory

### ISSUE THREAD

**Issue by hodzanassredin** [SuaveIO/suave#360] opened 2015-12-16 08:35 UTC
Trying to do load tests with Yandex.Tank rps_schedule=line(100,40000,2m)
with DefaultTcpServerFactory everything is ok and no errors at all. Ubuntu vm can handle to 4k rps.
But when I try to use LibUvServerFactory exceptions start to occur when load is more than 1400 rps and virtual users more than 31.
<img width="732" alt="benchs" src="https://cloud.githubusercontent.com/assets/40375/11836067/2846eea6-a3e9-11e5-8881-a794d2f09b79.png">

I need to note that kestrel which also uses libuv also does'n work well, it doesnt show errors and works but it cant handle more than 200 rps on the same machine. So probably there is a problem in config.
I installed libuv as described here https://docs.asp.net/en/latest/getting-started/installing-on-linux.html
I tested both suave versions from nuget and from master branch. 

```
let port = 80
let conf  = { defaultConfig with bindings = [ HttpBinding.mkSimple HTTP "0.0.0.0" port ];
                             tcpServerFactory = LibUvServerFactory()
                             bufferSize            = 2048
                             maxOps                = 100}


startWebServer conf (OK "Hello Suave")
```

```
[W] 2015-12-16T08:13:47.5331920Z: tcp request processing failed [Suave.Tcp.job] exn:
System.InvalidOperationException: Stack empty.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) <0x41a57190 + 0x00027> in <filename unknown>:0
  at System.Collections.Generic.Stack`1[T].Pop () <0x41a06040 + 0x0001f> in <filename unknown>:0
  at Suave.Sockets.BufferManager.PopBuffer (Microsoft.FSharp.Core.FSharpOption`1 context) <0x41a059a0 + 0x0005b> in <filename unknown>:0
  at Suave.Web+ParsingAndControl+readMoreData@115.Invoke (Microsoft.FSharp.Core.Unit unitVar) <0x41a11830 + 0x00087> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0015a> in <filename unknown>:0

Unhandled Exception:
System.InvalidOperationException: Stack empty.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) <0x41a57190 + 0x00027> in <filename unknown>:0
  at System.Collections.Generic.Stack`1[T].Pop () <0x41a06040 + 0x0001f> in <filename unknown>:0
  at Suave.Sockets.BufferManager.PopBuffer (Microsoft.FSharp.Core.FSharpOption`1 context) <0x41a059a0 + 0x0005b> in <filename unknown>:0
  at Suave.Tcp+job@108.Invoke (Microsoft.FSharp.Core.Unit unitVar) <0x41a053f0 + 0x00217> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0015a> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fc7d44016d0 + 0x00029> in <filename unknown>:0
  at Microsoft.FSharp.Control.CancellationTokenOps+Start@1268-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) <0x41a57900 + 0x0001e> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0040c> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+queueAsync@763[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x419f7120 + 0x000e6> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control.loop@430-54 (Microsoft.FSharp.Control.Trampoline this, Microsoft.FSharp.Core.FSharpFunc`2 action) <0x419f70b0 + 0x00032> in <filename unknown>:0
  at Microsoft.FSharp.Control.Trampoline.ExecuteAction (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6fd0 + 0x00067> in <filename unknown>:0
  at Microsoft.FSharp.Control.TrampolineHolder.Protect (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6e50 + 0x0009b> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control+-ctor@516-1.Invoke (System.Object state) <0x419f6ae0 + 0x0004b> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7fc7d44b5720 + 0x00048> in <filename unknown>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7fc7d44af850 + 0x0016e> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7fc7d44af820 + 0x00020> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7fc7d44b56b0 + 0x00053> in <filename unknown>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x7fc7d44b3cc0 + 0x001d6> in <filename unknown>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7fc7d44b5530 + 0x00008> in <filename unknown>:0

Unhandled Exception:
System.InvalidOperationException: Stack empty.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) <0x41a57190 + 0x00027> in <filename unknown>:0
  at System.Collections.Generic.Stack`1[T].Pop () <0x41a06040 + 0x0001f> in <filename unknown>:0
  at Suave.Sockets.BufferManager.PopBuffer (Microsoft.FSharp.Core.FSharpOption`1 context) <0x41a059a0 + 0x0005b> in <filename unknown>:0
  at Suave.Tcp+job@108.Invoke (Microsoft.FSharp.Core.Unit unitVar) <0x41a053f0 + 0x00217> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0015a> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fc7d44016d0 + 0x00029> in <filename unknown>:0
  at Microsoft.FSharp.Control.CancellationTokenOps+Start@1268-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) <0x41a57900 + 0x0001e> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0040c> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+queueAsync@763[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x419f7120 + 0x000e6> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control.loop@430-54 (Microsoft.FSharp.Control.Trampoline this, Microsoft.FSharp.Core.FSharpFunc`2 action) <0x419f70b0 + 0x00032> in <filename unknown>:0
  at Microsoft.FSharp.Control.Trampoline.ExecuteAction (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6fd0 + 0x00067> in <filename unknown>:0
  at Microsoft.FSharp.Control.TrampolineHolder.Protect (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6e50 + 0x0009b> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control+-ctor@516-1.Invoke (System.Object state) <0x419f6ae0 + 0x0004b> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7fc7d44b5720 + 0x00048> in <filename unknown>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7fc7d44af850 + 0x0016e> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7fc7d44af820 + 0x00020> in <filename unknown>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7fc7d44b56b0 + 0x00053> in <filename unknown>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x7fc7d44b3cc0 + 0x001d6> in <filename unknown>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7fc7d44b5530 + 0x00008> in <filename unknown>:0

Unhandled Exception:
System.InvalidOperationException: Stack empty.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) <0x41a57190 + 0x00027> in <filename unknown>:0
  at System.Collections.Generic.Stack`1[T].Pop () <0x41a06040 + 0x0001f> in <filename unknown>:0
  at Suave.Sockets.BufferManager.PopBuffer (Microsoft.FSharp.Core.FSharpOption`1 context) <0x41a059a0 + 0x0005b> in <filename unknown>:0
  at Suave.Tcp+job@108.Invoke (Microsoft.FSharp.Core.Unit unitVar) <0x41a053f0 + 0x00217> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0015a> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fc7d44016d0 + 0x00029> in <filename unknown>:0
  at Microsoft.FSharp.Control.CancellationTokenOps+Start@1268-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) <0x41a57900 + 0x0001e> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) <0x419f9510 + 0x0040c> in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+queueAsync@763[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x419f7120 + 0x000e6> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control.loop@430-54 (Microsoft.FSharp.Control.Trampoline this, Microsoft.FSharp.Core.FSharpFunc`2 action) <0x419f70b0 + 0x00032> in <filename unknown>:0
  at Microsoft.FSharp.Control.Trampoline.ExecuteAction (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6fd0 + 0x00067> in <filename unknown>:0
  at Microsoft.FSharp.Control.TrampolineHolder.Protect (Microsoft.FSharp.Core.FSharpFunc`2 firstAction) <0x419f6e50 + 0x0009b> in <filename unknown>:0
  at <StartupCode$FSharp-Core>.$Control+-ctor@516-1.Invoke (System.Object state) <0x419f6ae0 + 0x0004b> in <filename unknown>:0
  at System.Thr
```

**Comment by hodzanassredin** [comment] 2015-12-16 09:23
If you want to test code in your box just give me an url and I'll run tank against it.

**Comment by ademar** [comment] 2015-12-16 09:43
Thanks for doing this.

If you want to get rid of the errors just increase maxOps to a larger
number.

On Wednesday, 16 December 2015, Hodza Nassredin <notifications@github.com>
wrote:

> If you want to test code in your box just give me an url and I'll run tank
> against it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/360#issuecomment-165044354>.
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by hodzanassredin** [comment] 2015-12-16 10:43
Increased maxOps and yes no more erros but rps is verly low no more than 1-2 krps. Could you recommend some config values to play with?

**Comment by hodzanassredin** [comment] 2015-12-16 11:15
Something goes really weird with lubev. Process freezes and ctr-c doesnt work. I have to kill process. Is it ok to start suave from fsharpi?

**Comment by hodzanassredin** [comment] 2015-12-16 11:52
Tried compile server but no difference. And one more thing then I open this url in browser it takes about 145 ms to get response. But all other server usually do it in 65 ms. I don't know why. Unfortunately I have not ime to dig deeper but there is something wrong with libuv integration.

**Comment by hodzanassredin** [comment] 2015-12-18 13:30
Tested h2o server with the same libuv version on the same machine . more than 10 k rps. No errors.

**Comment by haf** [comment] 2015-12-18 19:27
Could you give a script to reproduce this? Like Yandex.Tank?

**Comment by hodzanassredin** [comment] 2015-12-21 08:19
Traffix source is ubuntu 14.04  vm 8 cores. 
Tandex tank installed as described here [Installation and Tuning sections](https://yandextank.readthedocs.org/en/latest/install.html)
After installation created load.ini file and started as yandex-tank -c load.ini.
You can find load.ini for yandex.tank and target vm (vm 8 cores) config files [here](https://gist.github.com/hodzanassredin/90ce5d5eb0b8fc2dc5e2)

**Comment by hodzanassredin** [comment] 2015-12-21 08:31
Target vm conf files are a little bit dirty for historical reasons. So they could be a reason of bad suave's and kestrel's behaviour with libuv.

**Comment by hodzanassredin** [comment] 2015-12-21 09:14
Off topic. My IMHO thoughts(probably incorrect) how to speed up suave.
During my work in an iot company(cars automation) we wrote a tcp/udp server. And unfortunately Task and Async is really bad in terms of performance and allocations. So simplest way to reduce costs is to use Hopac lib. Why allocations matter you can check (this)[https://github.com/valyala/fasthttp]. Next problem is libuv. I don't think that this is the best way to achieve performance at all. Some interesting info could be found in Haskell: (here)[https://ghc.haskell.org/trac/ghc/ticket/8400] and (here)[http://haskell.cs.yale.edu/wp-content/uploads/2013/08/hask035-voellmy.pdf]. Also you can check how golang does it (here)[https://golang.org/src/runtime/]  (all files netpoll*)

**Comment by 7sharp9** [comment] 2016-01-14 18:31
You can use wrk to profile, I too got a ton of errors like above:
```
wrk -t12 -c900 -d10s http://127.0.0.1:8086/
```

I actually get pretty poor performance on libuv and non libuv performance.

Last time I tried suave (non libuv) was 3x slower than a node js hello world and 25x slower then a rust iron hello world.  In fact I tried clojure and python hello worlds and Suave was the slowest I could find.

**Comment by polytypic** [comment] 2016-06-04 12:26
So, what is the story with performance?
Is async a source of performance issues in Suave?

Obviously I'm biased, but I think that, aside from familiarity, Hopac would be a very good fit for something like Suave.

**Comment by ademar** [comment] 2016-06-04 14:16
:)

Difficult to know what's going on here , very low in my radar right now.

I probably won't dedicate much more time to the libuv transport. Last time I checked the pure .net transport was performing better/faster. Marshaling impedance might be negating any performance gains libuv may have.

I don't think performance is a problem right now. Having said that it is totally possible in the future we bring Hopac into the mix.

**Comment by haf** [comment] 2016-06-04 16:29
I write all our backend code with Hopac, so for me it makes sense to bring Hopac into Suave in the long run, if that can be done in an orderly fashion which benefits the community.

Right now, people I work with reliably report Hopac to have a high getting-started threshold, so until that has been addressed I would not agree to a full-out change of Suave into Hopac.

The Command-Backend-Events cycle we're building at qvitoo is dependent on Suave and I hope we'll have some improvements to Suave to show for it over the summer. Either as a library or as some patterns of async handling. Hopac would make it easier to deal with and those patterns we publish could help lessen the learning threshold.

Another way would be to produce a set of paid and free videos detailing how to use Hopac with Suave; a natural use-case for async clients in browser (and native) single page applications.

As you probably see, I'm also more focused on making the web development story for Suave fit really well with people's expectations (and hopes!). What do you think Vesa?

**Comment by polytypic** [comment] 2016-06-05 08:53
I'm all for making Hopac more accessible.

I just spent quite a lot of time reordering, aligning and titling things in the generated [reference manual](http://hopac.github.io/Hopac/Hopac.html) with the intention of making it more accessible.

I've also been working on [improving interop](https://github.com/Hopac/Hopac/pull/100) with other .Net async facilities.  Note that the description doesn't currently describe all the changes.  I plan to get rid of the `Task`, `Async` and `IObservable` "extensions" and turn those into functions in the `Job` and `Alt` modules making them (I hope) more accessible and implementing them with simpler (and sometimes faster) semantics.

I'm also thinking of spending some time this summer to [eliminate the Scheduler abstraction](https://github.com/Hopac/Hopac/issues/84) and improve internal scheduling.  The changes will also reduce the library interface area as everything `Global` and `Scheduler` will basically vanish.

**Comment by neoeinstein** [comment] 2016-06-17 14:02
I'm all for helping to make the orderly switch to Hopac. Like @haf, I too generally use Hopac to back Suave, so I would be happy to assist in this.

**Comment by TheAngryByrd** [comment] 2016-08-04 18:40
I went through and did the **bare minimum** of changing Async to Jobs in Suave (https://github.com/TheAngryByrd/suave/commit/d64a4639085161c4394d841e3b1254b028470af5).  However when I did a benchmark (with the same test machine form https://github.com/Krzysztof-Cieslak/Suave.Kestrel/issues/1) I got a lower requests per second.  

I did not go any further than this.

**Comment by polytypic** [comment] 2016-08-04 22:09
I'd love to take a look and understand why Hopac performs poorly here.

So, what commands do I need to execute on OS X (or Windows haven't yet tried) to get a version of the benchmark running with async and jobs from scratch?

If I clone @TheAngryByrd 's Hopac branch and try the build instructions (bundle ...) I get errors.  Here is the first (of many many) errors I see:

```
/Users/vesakarv/Projects/Fs/suave/src/Suave.OpenSSL/OpenSSL.fs(208,11): error FS0001: This expression was expected to have type    Async<'a>    but here has type    SocketOp<unit>
```

**Comment by polytypic** [comment] 2016-08-05 06:29
I added a few comments to @TheAngryByrd Hopac branch and added a pair of new interop primitives to Hopac that might improve perf.  I can see that the code (both with async and job) could be optimized significantly.  I have not yet ran the benchmarks, because my quick attempts to build suave fail.  Building suave master, bundle fails when trying to install nokogiri:

```
$ bundle
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Using rake 10.5.0
Using map 6.6.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using semver2 3.4.2
Using bundler 1.12.5
Installing nokogiri 1.6.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/ext/nokogiri
/usr/local/opt/ruby/bin/ruby -r ./siteconf20160805-65611-ujj1cm.rb extconf.rb
Using pkg-config version 1.1.7
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for iconv.h... yes
checking for gzdopen() in -lz... yes
checking for iconv using --with-opt-* flags... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.4.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.4.tar.gz into tmp/x86_64-apple-darwin15.4.0/ports/libxml2/2.9.4... OK
Running 'configure' for libxml2 2.9.4... OK
Running 'compile' for libxml2 2.9.4... ERROR, review '/usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/ext/nokogiri/tmp/x86_64-apple-darwin15.4.0/ports/libxml2/2.9.4/compile.log' to see what happened. Last lines are:
========================================================================
    unsigned short* in = (unsigned short*) inb;
                         ^~~~~~~~~~~~~~~~~~~~~
encoding.c:815:27: warning: cast from 'unsigned char *' to 'unsigned short *' increases required alignment from 1 to 2 [-Wcast-align]
    unsigned short* out = (unsigned short*) outb;
                          ^~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
  CC       error.lo
  CC       parserInternals.lo
  CC       parser.lo
  CC       tree.lo
  CC       hash.lo
  CC       list.lo
  CC       xmlIO.lo
xmlIO.c:1450:52: error: use of undeclared identifier 'LZMA_OK'
    ret =  (__libxml2_xzclose((xzFile) context) == LZMA_OK ) ? 0 : -1;
                                                   ^
1 error generated.
make[2]: *** [xmlIO.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.3.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete compile task (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:111:in `compile'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
	from extconf.rb:364:in `block (2 levels) in process_recipe'
	from extconf.rb:257:in `block in chdir_for_build'
	from extconf.rb:256:in `chdir'
	from extconf.rb:256:in `chdir_for_build'
	from extconf.rb:363:in `block in process_recipe'
	from extconf.rb:262:in `tap'
	from extconf.rb:262:in `process_recipe'
	from extconf.rb:555:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.8/gem_make.out
An error occurred while installing nokogiri (1.6.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
```

I have not investigated this further.

**Comment by haf** [comment] 2016-08-05 06:51
@polytypic Googling a bit suggests you may not have run `xcode-select --install` on your OS X machine, to install the Apple dev tools/XCode.

**Comment by polytypic** [comment] 2016-08-05 07:56
@haf Thanks!  After that and reinstalling libuv (and running into http://bugs.python.org/issue18378) I managed to run Suave master build to completion.  So, then I need to get the Hopac branch built and run the benchmarks with it...

**Comment by haf** [comment] 2016-08-05 08:01
@polytypic No worries. For future reference you can use https://github.com/haf/osx to provision your machine in a way that works work most languages :) – includes fixes to the above issues.

**Comment by polytypic** [comment] 2016-08-05 19:57
I've now spent a little time looking at the changes and running the benchmarks.  It seems that the hot paths still contain Async code.  IOW, much of the leaf code or the routines that are called many times are still using Asyncs while some code in the middle uses Jobs. Converting/Transferring between Asyncs, Tasks and Jobs can be relatively expensive and now there are many unnecessary conversions/transfers per request.  This is likely the reason that the modified Suave runs slower.  To get good performance, one should use Task returning ops directly from Jobs.

**Comment by forki** [comment] 2016-08-26 10:47
So where are we with this? Anyone still working on it?

**Comment by TheAngryByrd** [comment] 2016-08-26 12:40
Since this weekend I'm not traveling ill have a chance to take another crack at it.

**Comment by forki** [comment] 2016-08-26 12:42
cool. so what's the goal?

**Comment by haf** [comment] 2016-08-26 13:21
@forki  To check where the hotspots are and whether we can bump the performance of Suave?

**Comment by TheAngryByrd** [comment] 2016-08-27 15:26
Using dottrace, , the thing that takes the longest in Suave is TcpTransport.write method.  (i know its windows only. I might try to use PrivateEye later on linux to see how they line up.)

![suaveperf](https://cloud.githubusercontent.com/assets/1490044/18026896/bcc8fef0-6c22-11e6-8698-c87359ed8cee.JPG)

I did these next benchmarks without a profiler attached.

This is the normal async version.  It tends to use about 50% of the CPU on windows and about 75% on linux. 
Normal hello world example on my test machines:
Windows/ net461: 13000 req/s
Linux/ mono 4.4.1: 6200 req/s

I tried moving it over to Hopac using some of the recommendations from @polytypic (https://github.com/TheAngryByrd/suave/commit/d64a4639085161c4394d841e3b1254b028470af5).  I started a new branch again just to be safe.  I also tried to remove as much Async/Task interop as I could for that path.  I'm sure I still missed some. This tends to use the max CPU it can on windows or linux.
Moving to all over to [Hopac](https://github.com/TheAngryByrd/suave/commits/hopac2) :
Windows/ net461: 14000 req/s
Linux/ mono 4.4.1: 3900 req/s

I dug around for mono/SendAsync info, found [this comment](https://github.com/xplicit/HyperFastCgi/issues/4#issuecomment-39850493) (it is 2 years old but might still apply).

Doing a **terrible terrible** hack 

```
   member this.write (buf : ByteSegment) =
      async{
        if acceptArgs.AcceptSocket = null then
         return Choice2Of2 (ConnectionError "write error: acceptArgs.AcceptSocket = null") 
       else
         let foo = ResizeArray<ByteSegment>([|buf|])
         acceptArgs.AcceptSocket.Send(foo) |> ignore
         return Choice1Of2 ()
         //return! asyncDo acceptArgs.AcceptSocket.SendAsync (setBuffer buf) ignore writeArgs
      }
```
Windows/ net461: 14000 req/s
Linux/ mono 4.4.1: 9400 req/s

I'll try digging around in the LibUV implementation later today to see if theres anything there too.

**Comment by TheAngryByrd** [comment] 2016-09-05 16:17
Since I know [Nowin](https://github.com/Bobris/Nowin) uses ScoketAsyncEventArgs.  I quickly took it for a spin.  I was able to get around ```60k req/s```. on my linux machine.

**Comment by forki** [comment] 2016-09-05 16:23
???

**Comment by hodzanassredin** [comment] 2016-09-15 08:42
Tested .net core latest version on ubuntu with yandex tank.
```
aspnetcore 10k rps
suave 2.0.0-alpha5 6k rps  (https://github.com/SuaveIO/Suave-CoreCLR-sample)
```
both started :  dotnet run  -c Release
Was not able to test suave libuv: Package Suave.LibUv 2.0.0-alpha5 is not compatible with netcoreapp1.0

**Comment by polytypic** [comment] 2016-09-15 09:10
I would recommend trying to wrap libuv with Hopac rather than Async / ThreadPool:

  https://github.com/Hopac/Hopac.libuv

If someone is interested and has time, I'd be happy to mentor such a project.  Otherwise I'll look at it (sooner or much) later.

**Comment by 7sharp9** [comment] 2016-09-15 10:19
@TheAngryByrd `SocketAsyncEventArgs` works quite well especially in Windows environments, it is an allocation free API, so you have to ensure the rest of the code touching that part is also allocation free.

**Comment by 7sharp9** [comment] 2016-09-15 10:22
Also `SocketAsyncEventArgs` is supposed to use IO completion ports more efficiently so you wont be using as much CPI, you normally max out the IO layer before the CPU.

**Comment by dsyme** [comment] 2016-09-16 16:09
@polytypic In https://github.com/fsharp/fsfoundation/pull/387 you said you were no longer supporting Hopac for public use.  Could you give updated guidance on this?  Are you now recommending it for public and production use?

**Comment by neoeinstein** [comment] 2016-09-16 17:11
@dsyme At the least, there are several people who are interested in supporting the continued development of Hopac, even if @polytypic only offered mentoring. I know that I am one of those people working to build on the solid foundation Hopac already provides.

**Comment by polytypic** [comment] 2016-09-18 20:12
@dsyme:

> You said you were no longer supporting Hopac for public use.  Could you give updated guidance on this?  Are you now recommending it for public and production use?

Those are fair questions.

I spent some time thinking about this.

Nothing has actually changed in that sense.  I originally started working on Hopac based on what I wanted and needed back then (more [here](https://gist.github.com/polytypic/6db1984fdf62b358afd2f82fab088013)) and I open sourced it because there appeared to be some interest in it.  As I don't use F# regularly on work projects, I've continued developing it (and some of my other F# projects) as a hobby.  Perhaps it is time to acknowledge that it no longer makes sense for me to put time into it.

I withdraw my recommendation to try to wrap libuv with Hopac.

**Comment by haf** [comment] 2016-09-18 20:35
@polytypic It's sad for me to hear you say that. The effort that you put in is helping make the F# language eco-system a better one. Despite you not working with Hopac at your day-job, you've continuously put enough effort into maintaining it, for it to be very relevant for at least my own open source projects. What you're doing as a hoppy has positive effects on the industry around this language – that's really saying something about the quality of your code and your vision.

**Comment by dsyme** [comment] 2016-09-28 11:26
@polytypic I understand your concerns.

There may be other options between "supported" and "don't use it" you might like to consider for Hopac.

Normally, people will trust an open source project and take dependencies on it if there are 2-3 top-level maintainers, and a sense of mutual commitment to longevity. Hopac offers real value, and there are definitely people interested in using it and contributing to it.  

Probably all it takes for Hopac is to onboard additional multiple top-level maintainers with necessary permissions to update the packages. Plus a design process and strong automated testing. Some people have found that moving projects to htp://github.com/fsprojects has been useful (e.g. for Fable), though I'm not sure you'd want that since you already have an independent github org.

Making this transition can be really hard though, especially for areas where strong lead over the design and implementation is needed.

**Closed** 2023-01-17 17:47 UTC
Labels: performance
