### ISSUE TITLE
Problems with Suave 2.2.0 and Liquid

### ISSUE THREAD

**Issue by mrkaspa** [SuaveIO/suave#642] opened 2017-08-17 13:54 UTC
I made a simple example and got this error

```fsharp
open DotLiquid
open Suave
open Suave.Filters
open Suave.Operators
open Suave.Successful
open Suave.DotLiquid

type Model =
  { title : string }

setTemplatesDir "./../templates"

let o = { title = "Hello World" }

let app =
  choose
    [ GET >=> choose
        [ path "/" >=> page "my_page.liquid" o ]]

startWebServer defaultConfig app
```

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Suave.DotLiquid' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Suave-DotLiquid>.$Suave.DotLiquid' threw an exception. ---> System.MissingFieldException: Field not found: 'DotLiquid.Template.NamingConvention'.
   --- End of inner exception stack trace ---
   at Suave.DotLiquid..cctor()
   --- End of inner exception stack trace ---
   at Suave.DotLiquid.setTemplatesDir(String dir)
   at <StartupCode$GitRankFs>.$Program.main@() in /Users/mrkaspa/code/GitRankFs/Program.fs:line 12
```

**Comment by haf** [comment] 2017-08-17 13:57
DotLiquid v2.0.55? https://www.nuget.org/packages/Suave.DotLiquid/

Could you submit a PR to bump DotLiquid please?

**Comment by mrkaspa** [comment] 2017-08-17 14:05
@haf with that dependency got this error when tries to render

```
[09:04:54 INF] Smooth! Suave listener started in 73.903 with binding 127.0.0.1:8080
[09:04:58 ERR] request failed
System.TypeLoadException: Could not load type 'Async' from assembly 'Suave, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'.
   at Suave.DotLiquid.renderPageFile[m](String fileFullPath, m model)
   at Suave.DotLiquid.page@183.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
```

**Comment by haf** [comment] 2017-08-17 14:15
Runtime?

**Comment by mrkaspa** [comment] 2017-08-17 14:17
dotnet core 2

**Comment by haf** [comment] 2017-08-17 14:18
It's supposed to bind to `module [<AutoOpen>] Suave.Utils.YoLo` which contains `Async.map`, which is failing for you. Binding should work, because this exists:

<img width="670" alt="screen shot 2017-08-17 at 16 17 26" src="https://user-images.githubusercontent.com/193115/29416822-98b6aabe-8367-11e7-88da-5fef1b9017ce.png">

And because it all compiles on both mono and .net core. I did build it using .Net core of a previous version though.

**Comment by haf** [comment] 2017-08-17 14:18
```
$ dotnet --version
1.0.4
```

For me.

**Comment by haf** [comment] 2017-08-17 14:19
I'd update, but there are no command line instructions at https://www.microsoft.com/net/core#macos

**Comment by haf** [comment] 2017-08-17 14:20
PIng @enricosada – what would be my next steps?

**Comment by haf** [comment] 2017-08-17 14:22
Also ping @ademar – are we moving to .Net core 2.0?

**Comment by haf** [comment] 2017-08-17 14:22
@mrkaspa If you could PR that bump of DotLiquid meanwhile, I could get that merged.

**Comment by mrkaspa** [comment] 2017-08-17 14:30
@haf what do you mean? should I create the issue in DotLiquid?

**Comment by haf** [comment] 2017-08-17 14:33
No, I'm thinking you could bump the version of DotLiquid in this repo and send that as a PR. That way the CI infrastructure can test it out.

**Comment by haf** [comment] 2017-08-17 14:33
Related https://github.com/SuaveIO/suave/issues/639 https://github.com/SuaveIO/suave/issues/637 https://github.com/SuaveIO/suave/issues/609

**Comment by jimfoye** [comment] 2017-08-17 14:39
That TypeInitializationException is exactly what I was seeing in #641.

**Comment by mrkaspa** [comment] 2017-08-20 19:28
is there a solution for this? may be another template system?

**Comment by haf** [comment] 2017-08-20 20:06
@mrkaspa Could you try the new release v2.2.1 where I bumped the dependency, to start with?

**Comment by haf** [comment] 2017-08-20 20:15
Besides that, I'm having trouble building Suave with .Net Core 2.0, so I can't try recompiling it right now.

**Comment by mrkaspa** [comment] 2017-08-20 20:19
@haf got problems with that version too

**Comment by haf** [comment] 2017-08-20 20:28
@mrkaspa I see. Thanks for letting us know.

Yes, there are other backends, like Razor, Suave.Experimental and the one that is currently a PR since yesterday (see PR #644) 

Of course it would be optimal to sort this issue out; if you'd feel up for digging about the internals of cross-platform cross-runtime builds, so I don't have to ;)

**Comment by mrkaspa** [comment] 2017-08-20 21:09
@haf honestly I'm a f# beginner learning the language and wanted to build a small experiment web site, so I can't be much help

**Comment by haf** [comment] 2017-08-20 22:03
Of course. Then I'd recommend https://www.gitbook.com/book/theimowski/suave-music-store/details which uses the F# view engine.

**Comment by ademar** [comment] 2017-08-20 22:53
> Also ping @ademar – are we moving to .Net core 2.0?

I'll leave that decision to you. I am still running my stuff in old .NET/Mono

**Comment by mrkaspa** [comment] 2017-08-21 00:37
@haf the guide is too outdated it uses Suave 1

**Comment by mrkaspa** [comment] 2017-08-21 05:50
@haf this works with on the 2.0.4 version but from 2.0.5  starts breaking with this error

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Suave, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by haf** [comment] 2017-08-21 06:36
@mrkaspa I think the view engine docs of that guide are pretty much up to date.

You last message doesn't contain enough information to debug.

I suggest you start with mono and await someone who works with .Net Core to come by and help out with these loader errors.

**Comment by matthid** [comment] 2017-08-21 07:00
The `Could not load file or assembly 'Suave ...` is probably https://github.com/SuaveIO/suave/issues/635
I'm unsure about the initial reported errors...

**Comment by manio143** [comment] 2017-08-21 11:22
I'm running on Mono and saw the same issues with Suave.DotLiquid, throwing the initializer exception. However, when I dropped the nuget package and simply included `Suave.DotLiquid/Library.fs` into my project it works fine with DotLiquid 2.0.168
So the problem is probably with the Suave.DotLiquid package rather then the source code.
But I have no idea what might the problem be.

**Comment by jimfoye** [comment] 2017-08-22 22:35
From the readme.txt for DotLiquid:

> `INamingConvention` have now a new member: `bool OperatorEquals...

Almost certainly this is the culprit.

**Comment by inosik** [comment] 2017-08-23 13:55
The reason for this is that somewhere between DotLiquid 2.0.55 and 2.0.168, [`DotLiquid.Template.NamingConvention`][code] changed from being a public static _field_ to a public static _property_.

  [code]: https://github.com/SuaveIO/suave/blob/e8428ca21a2dd28aa9f08609081ca656f8669e6e/src/Suave.DotLiquid/Library.fs#L22

Although the DotLiquid package is referenced from Pakets Main group in Suave.DotLiquid, the `net40` assembly gets compiled against 2.0.64:
```
.assembly extern DotLiquid
{
  .publickeytoken = (82 E4 60 16 EC F9 F0 7C )                         // ..`....|
  .ver 2:0:64:0
}
```

And the `netstandard1.6` one against 2.0.55:
```
.assembly extern DotLiquid
{
  .publickeytoken = (82 E4 60 16 EC F9 F0 7C )                         // ..`....|
  .ver 2:0:55:0
}
```

The .NET Standard project [references 2.0.55][2055], but the .NET Framework project should [reference 2.0.158][20158]. I think there is some MSBuild reference resolution magic going on here, which spits 2.0.64 into the mix. [2.0.64 is resolved in the "Tests" dependency group][2064].

  [2055]: https://github.com/SuaveIO/suave/blob/e8428ca21a2dd28aa9f08609081ca656f8669e6e/src/Suave.DotLiquid/Suave.DotLiquid.netcore.fsproj#L20
  [20158]: https://github.com/SuaveIO/suave/blob/e8428ca21a2dd28aa9f08609081ca656f8669e6e/paket.lock#L4
  [2064]: https://github.com/SuaveIO/suave/blob/e8428ca21a2dd28aa9f08609081ca656f8669e6e/paket.lock#L176

So I think the DotLiquid package needs to be updated everywhere: in every Paket group and in the [`Suave.DotLiquid.netcore`][proj].

  [proj]:
 https://github.com/SuaveIO/suave/blob/master/src/Suave.DotLiquid/Suave.DotLiquid.netcore.fsproj

**Comment by inosik** [comment] 2017-08-23 14:01
Using [Pakets `strategy: min` option][strategy] could also fix this.

  [strategy]: https://fsprojects.github.io/Paket/dependencies-file.html#Resolver-strategy-for-transitive-dependencies

**Comment by haf** [comment] 2017-08-23 14:03
If you have a working environment; it would be great if you could PR some of that.

**Comment by inosik** [comment] 2017-08-23 14:10
Unfortunately, I don't. I just looked into the assemblies with ILDasm.

**Closed** 2017-09-05 16:06 UTC
Labels: infra, x-platform
