### ISSUE TITLE
Suave.io/F# timeouts in Azure Web Apps

### ISSUE THREAD

**Issue by mredison** [SuaveIO/suave#614] opened 2017-04-26 22:21 UTC
Hello folks. I hope you can help me with a customer issue.

The application is written in F# and uses the suave.io web server and uses various type providers (such as the JSON type provider).  But the issue seems to be when making longer running calls to ADW and for that customer is using standard SQL command from .NET

This is his web.config:
<httpPlatform stdoutLogEnabled="true" stdoutLogFile=”RestAPI.log" startupTimeLimit="200" processPath="%HOME%\site\wwwroot\RestAPI.exe" arguments="%HTTP_PLATFORM_PORT% .">

My recommendation was to increase the requestTimeout in httpPlatform tag.
Customer increased the timeout to 10 minutes but he is getting new errors:

Get-Observed : The remote server returned an error: (500) Internal Server Error.
Response from http://*****.azurewebsites.net/observation/UserCount?*******:
<html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
At line:1 char:1
+ Get-Observed -forest namprd03 -Protocol EAS -activity All -window 1 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Observed], WebException
    + FullyQualifiedErrorId : System.Net.WebException,PSCustomerImpact.GetObserved

Looking at the RestAPI.log file customer can see the request being made and the call going out to the backend at 10:44 PM (UTC).  The client gets the 500 error at around 10:47 PM.  And RestAPI then reports success from the backend call at 10:49 PM.  It seems that there is some other timeout happening at around 3 to 4 minutes as I set the requestTimeout to 10 minutes.

The call to the backend for this particular query takes about 5 minutes.  When customer points the client to his local web server the client is able to complete the request – it still takes 5 minutes as both his local and the azure REST service are using the same Azure backend. 

Have you seen this issue before?

Any help will be appreciated it.

Thanks

Best Regards

**Comment by haf** [comment] 2017-04-27 06:44
I think tcp timeouts are around 90 seconds. 

Can you rewrite the service keep state around and then poll from the client?

**Comment by Samvrie** [comment] 2017-04-28 11:09
Hi,
Just for clarification do you mean the variable **executionTimeout** in your web.config when you say **requestTimeout**?
the default timeout for a request is 180 which is 3 Minutes like in your case.

**Comment by ademar** [comment] 2017-04-28 12:48
Can you share the code of your app ? Is there a catch-all route handler ? Usually `NOT_FOUND "Found no handlers"`

If there is no handler for the requested path Suave wont answer at all.

**Comment by mredison** [comment] 2017-04-28 17:04
Hi all, thanks for your reply. 

I am checking some Azure Web Apps guidelines that there is a max request time of 230 seconds. Any HTTP request can’t run for more than 230 seconds without any data transfer. That limit actually comes from an underlying Azure Networking limit of no idle open connections for more than 240 seconds. If we don’t kill the request with 500 on the 230 second mark, you’ll get connection closed at the 240 second mark. 

I will review this statement with customer and upload a piece of code. 

Thanks

**Comment by eknutsen3** [comment] 2017-04-28 17:54
The issue isn’t with the handlers.  The request works fine outside of azure (I host a local instance of the web server on my dev box).  The issue is that Azure, as per the Web App guidelines, is killing the connection.  Basically, the web service makes a call to the DB and that call is taking > 5 minutes but Azure kills the client connection to the web app at the 230 second mark.

I get no errors from the app as the request to the DB finishes successfully and the app processes the data successfully but the client is gone so the app just throws away the data.  Basically, the client gets a 500 but the app thinks nothing went wrong - other than the client went away.

I am not sure how to keep the connection open.

**Comment by eknutsen3** [comment] 2017-04-28 17:59
I should add, the vast majority (99%) of the calls to the DB complete in < 120 seconds.  The 500 error is an edge case.

**Comment by haf** [comment] 2017-04-28 19:06
Well, I'd say we close this as by the design of networks in general. Long running commands need to push data; I suggest you use [Suave's EventSource](https://suave.io/Suave.html#def:module%20Suave.EventSource) to keep sending data to the client to avoid the issue of the azure load balancer terminating the request.

**Closed by haf** 2017-04-28 19:06 UTC
