### ISSUE TITLE
Referencing Razor on Azure WebSite machine

### ISSUE THREAD

**Issue by tpetricek** [SuaveIO/suave#247] opened 2015-05-14 14:11 UTC
I was trying to use Suave.Razor on a Azure WebSite machine - this was through `app.fsx` script that was executed by FAKE. However, I was getting the following error:

> Could not load file or assembly 'System.Web.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference

This is a bit weird because (AFAIK) there is no version of this library in GAC on the machine and RazorEngine references version 3.0.0.0 (so I actually do not get why it would even try loading version 2.0.0.0).

But I know that @matthid was debugging the same error in F# Formatting, so perhaps he can help us with this! @matthid - do you know what was the core of the problem? I tried to force load Razor (see the three [Razor related commits here](https://github.com/tpetricek/suave-fshome/commits/master)), but I'm not sure I was doing the same thing as you in F# Formatting. 

Getting this to work would be very nice - using Suave with Razor was pretty nice experience :-). Though we could try supporting DotLiquid as a more light-weight alternative.

**Comment by matthid** [comment] 2015-05-14 14:39
There is a bunch of possible causes for this:

- https://github.com/tpetricek/suave-fshome/commit/b6b47c55c3a209ce1adc9670e93958f9259d071b#diff-d94823f9d153c0e3fc375dd995ba9a7bR7 Either use the "net45" RazorEngine build in combination with Razor3 or "net40" with Razor2. Mixing this up will not work.
- FAKE itself brings a Razor-2 dependency (https://github.com/fsharp/FAKE/blob/master/paket.dependencies) so there is definitely a hidden pitfall as well if you depend on this part of FAKE. 

I hope this helps identifying the issue!

**Comment by tpetricek** [comment] 2015-05-14 14:58
@matthid - Thanks! I did not realize the package has two different versions - that must be it....

**Comment by haf** [comment] 2015-05-21 07:48
Did this issue resolve itself?

**Comment by tpetricek** [comment] 2015-05-21 20:01
Not yet…

 

I did try changing the path (to the 45 version rather than 40 version), but then I started getting another error (sorry, don’t have an exact log, but it was saying something along the lines of “inheritance access violation”). So, I think I (or someone else!) need to look more into this.

**Comment by haf** [comment] 2015-10-13 10:58
Closing until it's clear what the issue is about. More info -> open again.

**Closed by haf** 2015-10-13 10:58 UTC
