### ISSUE TITLE
Suave.DotLiquid potential assembly version mismatch

### ISSUE THREAD

**Issue by RussBaz** [SuaveIO/suave#637] opened 2017-08-04 06:27 UTC
I am getting the following issue at runtime when I am trying to follow the dotliquid sample from https://suave.io/dotliquid.html

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Suave, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Program.main(String[] argv)
```
I am using F# on net core (2.0 preview) with paket.
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)      
                                                     
Product Information:                                 
 Version:            2.0.0-preview2-006497           
 Commit SHA-1 hash:  06a2093335                      
                                                     
Runtime Environment:                                 
 OS Name:     Windows                                
 OS Version:  10.0.15063                             
 OS Platform: Windows                                
 RID:         win10-x64                              
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-previ
                                                     
Microsoft .NET Core Shared Framework Host            
                                                     
  Version  : 2.0.0-preview2-25407-01                 
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

paket --version
Paket version 5.84.0

paket.dependencies:
```
source https://www.nuget.org/api/v2
framework: netcoreapp2.0

nuget Suave
nuget Suave.DotLiquid
nuget DotLiquid
```

paket.references
```
Suave
Suave.Dotliquid
Dotliquid
```

fsproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

Thank you.

**Comment by rmunn** [comment] 2017-08-07 09:48
I believe this is caused by #635.

**Comment by haf** [comment] 2017-08-16 06:34
Should have been fixed with #640, let me recompile & release and let's see if it's indeed fixed.

**Comment by rmunn** [comment] 2017-08-17 02:05
@haf - Looks like the Appveyor build failed while running the libuv unit tests. Do you have a way to "kick" Appveyor and get it to redo that build? Right now the NuGet package available on nuget.org is still the 2.1.1 version with 0.0.0.0, so I can't yet verify that #635 has actually been fixed.

**Comment by haf** [comment] 2017-08-17 09:59
https://ci.appveyor.com/project/haf/suave/build/2.0.707 builds for me

**Comment by haf** [comment] 2017-08-17 10:02
Ok, releasing v2.2.0 despite the extra parameter to create potentially being incompatible with callers.

**Closed** 2018-02-10 13:54 UTC
Labels: bug-major
